const { lightTokens, darkTokens } = require('./src/tokens');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/**/*.{ts,tsx}',
    '../../packages/react/src/**/*.{ts,tsx}',
    '../../packages/docs/**/*.{ts,tsx}',
    '../../packages/playground/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: lightTokens.colors.primary[50],
          100: lightTokens.colors.primary[100],
          200: lightTokens.colors.primary[200],
          300: lightTokens.colors.primary[300],
          400: lightTokens.colors.primary[400],
          500: lightTokens.colors.primary[500],
          600: lightTokens.colors.primary[600],
          700: lightTokens.colors.primary[700],
          800: lightTokens.colors.primary[800],
          900: lightTokens.colors.primary[900],
          dark: {
            50: darkTokens.colors.primary[50],
            100: darkTokens.colors.primary[100],
            200: darkTokens.colors.primary[200],
            300: darkTokens.colors.primary[300],
            400: darkTokens.colors.primary[400],
            500: darkTokens.colors.primary[500],
            600: darkTokens.colors.primary[600],
            700: darkTokens.colors.primary[700],
            800: darkTokens.colors.primary[800],
            900: darkTokens.colors.primary[900],
          },
        },
        secondary: {
          50: lightTokens.colors.secondary[50],
          100: lightTokens.colors.secondary[100],
          200: lightTokens.colors.secondary[200],
          300: lightTokens.colors.secondary[300],
          400: lightTokens.colors.secondary[400],
          500: lightTokens.colors.secondary[500],
          600: lightTokens.colors.secondary[600],
          700: lightTokens.colors.secondary[700],
          800: lightTokens.colors.secondary[800],
          900: lightTokens.colors.secondary[900],
          dark: {
            50: darkTokens.colors.secondary[50],
            100: darkTokens.colors.secondary[100],
            200: darkTokens.colors.secondary[200],
            300: darkTokens.colors.secondary[300],
            400: darkTokens.colors.secondary[400],
            500: darkTokens.colors.secondary[500],
            600: darkTokens.colors.secondary[600],
            700: darkTokens.colors.secondary[700],
            800: darkTokens.colors.secondary[800],
            900: darkTokens.colors.secondary[900],
          },
        },
        background: lightTokens.colors.background,
        foreground: lightTokens.colors.foreground,
        muted: lightTokens.colors.muted,
        'muted-foreground': lightTokens.colors.mutedForeground,
        accent: lightTokens.colors.accent,
        'accent-foreground': lightTokens.colors.accentForeground,
        border: lightTokens.colors.border,
        destructive: lightTokens.colors.destructive,
        'destructive-foreground': lightTokens.colors.destructiveForeground,
        ring: lightTokens.colors.ring,
        dark: {
          background: darkTokens.colors.background,
          foreground: darkTokens.colors.foreground,
          muted: darkTokens.colors.muted,
          'muted-foreground': darkTokens.colors.mutedForeground,
          accent: darkTokens.colors.accent,
          'accent-foreground': darkTokens.colors.accentForeground,
          border: darkTokens.colors.border,
          destructive: darkTokens.colors.destructive,
          'destructive-foreground': darkTokens.colors.destructiveForeground,
          ring: darkTokens.colors.ring,
        },
      },
      spacing: {
        'xs': lightTokens.spacing.xs,
        'sm': lightTokens.spacing.sm,
        'md': lightTokens.spacing.md,
        'lg': lightTokens.spacing.lg,
        'xl': lightTokens.spacing.xl,
        '2xl': lightTokens.spacing['2xl'],
        '3xl': lightTokens.spacing['3xl'],
        '4xl': lightTokens.spacing['4xl'],
      },
      borderRadius: {
        none: lightTokens.borderRadius.none,
        sm: lightTokens.borderRadius.sm,
        md: lightTokens.borderRadius.md,
        lg: lightTokens.borderRadius.lg,
        full: lightTokens.borderRadius.full,
      },
      fontSize: {
        xs: lightTokens.fontSize.xs,
        sm: lightTokens.fontSize.sm,
        base: lightTokens.fontSize.base,
        lg: lightTokens.fontSize.lg,
        xl: lightTokens.fontSize.xl,
        '2xl': lightTokens.fontSize['2xl'],
        '3xl': lightTokens.fontSize['3xl'],
        '4xl': lightTokens.fontSize['4xl'],
      },
      fontWeight: {
        light: lightTokens.fontWeight.light,
        normal: lightTokens.fontWeight.normal,
        medium: lightTokens.fontWeight.medium,
        semibold: lightTokens.fontWeight.semibold,
        bold: lightTokens.fontWeight.bold,
      },
      lineHeight: {
        tight: lightTokens.lineHeight.tight,
        normal: lightTokens.lineHeight.normal,
        relaxed: lightTokens.lineHeight.relaxed,
        loose: lightTokens.lineHeight.loose,
      },
    },
  },
  plugins: [],
};